### ISSUE TITLE
I can't get the correct result

### ISSUE THREAD

**Issue by Lincoln20030413** [fatheral/matlab_imresize#11]
My input image shape is [32,3,64,64], but the shape of result is [64,6,64,64] while it should be [32,3,128,128]
Did my modification cause it? 
When I run the original code, a mistake happened: ValueError: operands could not be broadcast together with shapes (64,4,1,1) (64,4,3,64,64)
The mistake happens in the sentence:   outimg =  np.sum(weights*((inimg[indices].squeeze(axis=1)).astype(np.float64)), axis=1)

def imresizevec(inimg, weights, indices, dim):
    wshape = weights.shape
    if dim == 0:
        weights = weights.reshape((wshape[0], wshape[2], 1, 1)) 
        print(weights.shape)
        outimg =  np.sum(weights*((inimg[indices].squeeze(axis=1)).astype(np.float64)), axis=1)
        print(outimg.shape)

So I change  the "weights = weights.reshape((wshape[0], wshape[2], 1, 1))" to "weights = weights.reshape((wshape[0], wshape[2], 1, 1,1))"
Could you help me? Thanks a lot.

**Comment by fatheral** [comment]
The code is for a **single** image, not a batch of it. And dimensions are in the form of [height, width, depth].

**Comment by Lincoln20030413** [comment]
I see. Thank you very much.
