### ISSUE TITLE
Do you know how to back propagation of imresize with bilinear interpolation?

### ISSUE THREAD

**Issue by henanjun** [fatheral/matlab_imresize#2]
Thank you very much. :)

**Comment by fatheral** [comment]
I think you'd better to use the functions implemented in the NN Frameworks specially designed to have backprop :) E.g. [resize_images](https://www.tensorflow.org/api_docs/python/tf/image/resize_images) in TF.
Also you could look onto https://github.com/iwyoo/bicubic_interp-tensorflow

**Comment by henanjun** [comment]
Thank you very much. I see.
