### ISSUE TITLE
Adding LICENSE to repository

### ISSUE THREAD

**Issue by Imvoo** [fatheral/matlab_imresize#8]
I was interested in using your library as it mimics Matlab's imresize perfectly, however I noticed that there was no license attached to the project/repo.

Github's default policy for this is (taken from https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository):

> without a license, the default copyright laws apply, meaning that you retain all rights to your source code **and no one may reproduce, distribute, or create derivative works from your work**

Have you considered adding a license so that others (including myself) can use your source code in our own projects?

Thanks!

**Comment by fatheral** [comment]
Thanks, added MIT license.

**Comment by Imvoo** [comment]
Thanks for that!
